[build]
  publish = "dist" # pas aan als je build output anders heet
  command = "npm run build"

# Zorgt ervoor dat URL's altijd met een slash eindigen
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/index.html"
  to = "/nl/"
  status = 301
  force = true

[[redirects]]
  from = "/about.html"
  to = "/nl/over/"
  status = 301
  force = true

[[redirects]]
  from = "/pricing.html"
  to = "/nl/prijzen/"
  status = 301
  force = true

[[redirects]]
  from = "/portfolio.html"
  to = "/nl/portfolio/"
  status = 301
  force = true

[[redirects]]
  from = "/:path(.+).html"
  to = "/nl/"
  status = 301
  force = true

# Headers
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
